name: flutter_layout_video_vlc
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  flutter_vlc_player: ^6.0.4
  flutter_svg: ^0.22.0
  flutter_statusbar_manager: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/sample.mp4
    - assets/images/initial01.jpeg
    - assets/images/initial02.jpeg
    - assets/images/initial03.jpeg
    - assets/images/backgroundP.png
    - assets/images/logo.svg
    - assets/images/logo.png
    - assets/images/marca-dagua-P.svg
    - assets/icons/icon-arrow.svg
    - assets/icons/icon-lock.svg
    - assets/icons/icon-message.svg
    - assets/icons/icon-profile.svg
    - assets/icons/icon-calendar.svg
    - assets/icons/icon-profile.svg
    - assets/icons/icon-setting.svg
    - assets/icons/icon-show.svg
    - assets/icons/icon-camera.svg
    - assets/images/class01.jpeg
    - assets/images/class02.jpeg
    - assets/images/class03.jpeg
    - assets/icons/icon-seta.svg
    - assets/icons/icon-play.svg
    - assets/icons/icon-voice.svg
    - assets/video/01.mp4
    - assets/video/02.mp4
    - assets/icons/icon-play.svg
    - assets/icons/icon-play-big.svg
    - assets/icons/icon-expandir.svg
    - assets/icons/icon-avancar-10s.svg
    - assets/icons/icon-voltar-10s.svg
    - assets/icons/icon-volume-up.svg
    - assets/icons/icon-volume-off.svg
    - assets/images/Pedro-paixao-prof.png
    - assets/icons/icon-seta.svg
    - assets/icons/icon-logo.png
    - assets/icons/icon-pause.svg
    - assets/icons/icon-som-off.svg
    - assets/icons/icon-time.svg
    - assets/icons/icon-intensidade.svg
    - assets/icons/icon-next.svg
    - assets/icons/icon-pause.svg
    - assets/icons/icon-stop.svg
    - assets/icons/icon-checkbox-off.svg
    - assets/icons/icon-checkbox-on.svg
    - assets/icons/icon-pause-small.svg
    - assets/icons/icon-time.svg
    - assets/icons/icon-chat.svg
    - assets/icons/pause_clean.png
    - assets/icons/play_clean.png
    - assets/icons/logo_ios.png
    - assets/icons/icon-share.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
